### ISSUE TITLE
Need add support for VueJS files

### ISSUE THREAD

**Issue by sattellite** [preslavmihaylov/todocheck#107]
VueJS have one-file components with file extension `.vue`. One-file components contains html, javascript and css.

JS have standard comments and `.js` is supported by todomatcher: 
```javascript
// oneline comment
/*
multiline comment
*/
```

With preprocessors html and css can have different syntaxes 😞 https://vue-loader.vuejs.org/guide/pre-processors.html 
But it can be parsed as defualt html and css comments:

```html
<!-- HTML oneline and multiline comments -->
```
```css
/* CSS oneline and multiline comments */
```

**Comment by preslavmihaylov** [comment]
@sancroth if you're looking for a more challenging issue, you can check this one out. :)

It will require you to learn about state machines & extend the existing set of state machines for parsing comments.

**Comment by sancroth** [comment]
@preslavmihaylov i'll move on to this one if you want to assign someone.

**Comment by preslavmihaylov** [comment]
Go ahead!

**Comment by FelixTheodor** [comment]
If the issue ist still open, I'd like to try and solve it. My first impression is that I 'just' need to add a new ToDoMatcher for .vue files, matching all the mentioned formats, right?

**Comment by preslavmihaylov** [comment]
That is correct. The difficulty is in identifying HTML comments as identifying them requires that you read 4 symbols, while the current interface for creating todo matchers only enables you to read prev, curr and next symbols.

In the new todomatcher, you'll need to keep track of the second to current character in order to solve this. At least that's what it looks like at first glance.

Feel free to take this on.
