### ISSUE TITLE
Options for people running binary from old machine with no root privileges

### ISSUE THREAD

**Issue by SiliconKite** [preslavmihaylov/todocheck#43]
Hi, first of all thanks for this tool, looks pretty cool

I can't get it to work though. I am getting the following error when running the linux x86 binary

```
panic: (config.IssueTracker) (0x6f2420,0xc00018b020)

goroutine 1 [running]:
github.com/preslavmihaylov/todocheck/authmanager.acquireAPIToken.func1(0x7653e6, 0x14, 0x0, 0x0, 0xa17120)
	/Users/pmihaylov/programming/repos/todocheck/authmanager/authmanager.go:50 +0x24a
github.com/preslavmihaylov/todocheck/authmanager.acquireToken(0xc000188ec0, 0xc0001b2840, 0x17, 0xc00010de40, 0x4d1b50, 0xc0001fa000)
	/Users/pmihaylov/programming/repos/todocheck/authmanager/authmanager.go:78 +0x2be
github.com/preslavmihaylov/todocheck/authmanager.acquireAPIToken(0xc000188f00, 0x0, 0x0)
	/Users/pmihaylov/programming/repos/todocheck/authmanager/authmanager.go:39 +0x63
github.com/preslavmihaylov/todocheck/authmanager.AcquireToken(0xc000188f00, 0x11, 0x76064a)
	/Users/pmihaylov/programming/repos/todocheck/authmanager/authmanager.go:30 +0xb6
main.main()
	/Users/pmihaylov/programming/repos/todocheck/main.go:33 +0x243
```

My .todocheck.yaml is pointing to a private gitlab server.

Note that I am NOT running it from `/usr/local/bin` as I do not have access there. Any chance you can

1. Since I am running it in an old machine and this might be causing an issue, list what are the requirements.
2. Clarify whether the tool can be run from a different location ?

Thanks

**Comment by preslavmihaylov** [comment]
The issue seems to be that you have specified an issue tracker which is not supported. Available options can be found [here](https://github.com/preslavmihaylov/todocheck#supported-issue-trackers). Double-check that your `issue_tracker` line is correct in `.todocheck.yaml`.

Additionally, you are using a private Gitlab instance, which is not supported in the latest release (v0.2.0) but will be supported in the next one and support is already added to `master`.

You can download the latest master & compile from source (`go build`) or you can download the binary for your platform in the zip I've linked in [this issue](https://github.com/preslavmihaylov/todocheck/issues/40)

**Comment by preslavmihaylov** [comment]
Hey @SiliconKite did you try the steps I outlined above?

Are you experiencing any follow-up issues?

**Comment by SiliconKite** [comment]
Hi Preslav,
thanks a mill for the suggestions. I did not had the chance to try them yet
as i am on holidays atm. Will come back to you on this
thanks!

**Comment by preslavmihaylov** [comment]
@SiliconKite since there is no follow-up on the task I am closing this for now.

If you do experience any further issues, feel free to ping me or create a new issue \w description.
